### ISSUE TITLE
[FEATURE] escape unsuported ANSI attributes

### ISSUE THREAD

**Issue by aladjadj** [softwarefactory-project/re-ansi#1]
Actual: For the moment the lib use 3/4bits colors ANSI
In the case of ANSI attribute not match 3/4 bits, the chars are visible like `[4m`

`  on instances_zookeeper.tf line 69, in resource "aws_security_group" "zookeeper":
     [4maws_security_group.log.*.id,`
  
 Feature: waiting for support for more colors, it's maybe a good idea to escape ANSI pattern not supported 
 
 `  on instances_zookeeper.tf line 69, in resource "aws_security_group" "zookeeper":
      aws_security_group.log.*.id,`
      
 Thx a lot

**Comment by TristanCacqueray** [comment]
Thank you for the feedback. I've added support for the `[4m` sequence in the PR #2. Let me know if that works for you, and I can publish it as a new release soon.

It would be nice to skip unknown patterns, but I don't how to get the length of such pattern. If this is possible, this could be implemented here: https://github.com/softwarefactory-project/re-ansi/blob/7aabeaedd13c06d9bb19c5c278eb259663d8920f/src/Ansi.re#L228-L230

**Comment by aladjadj** [comment]
You are so fast!
I'm try asap, and if i've other case, i can try to add this in a new PR

**Comment by aladjadj** [comment]
Also have detected unknown pattern print by xcodebuild

`[17:59:29]: ▸ [39;1mClean Succeeded`

I think is first reset color and add bold ?

**Comment by TristanCacqueray** [comment]
Thank you for the report, feel free to open new issues so that it is easier to track. I've left a suggestion on #3 .

**Comment by TristanCacqueray** [comment]
The version 0.4.0 should contain both fixes, thanks again for the feedback.
https://www.npmjs.com/package/@softwarefactory-project/re-ansi/v/0.4.0
